name: Exercice 07 Workflow
on: [push, workflow_dispatch]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get Source Code
        uses: actions/checkout@v6
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "25.2.1"
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Test Building
        run: ls build/index.html

  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get Source Code
        uses: actions/checkout@v6
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "25.2.1"
      - name: Install dependencies
        run: npm ci
      - name: Run Unit tests
        run: npm run test
